- hosts: vm
  tasks:
    - name: install qemu-guest-agent
      become: true
      apt:
        name: qemu-guest-agent
        state: latest
    - name: check qemu service status
      become: true
      service:
        name: qemu-guest-agent
        state: started
