- hosts: vm
  become: true
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: latest
    - name: check qemu service status
      service:
        name: qemu-guest-agent
        state: started